3

diff --git a/.github/workflows/check-supposed-version.yml b/.github/workflows/check-supposed-version.yml
--- a/.github/workflows/check-supposed-version.yml
+++ b/.github/workflows/check-supposed-version.yml
@@ -11,10 +11,6 @@ on:
 jobs:
   enforce-label:
     name: Supposed version not exist
-    if: |
-      contains(github.event.pull_request.labels.*.name, 'major')
-      || contains(github.event.pull_request.labels.*.name, 'minor')
-      || contains(github.event.pull_request.labels.*.name, 'patch')
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -31,6 +27,16 @@ jobs:
       - name: Check patch label
         if: contains(github.event.pull_request.labels.*.name, 'patch')
         run: echo "CORRECT_LABEL=$(echo "patch")" >> $GITHUB_ENV
+
+      - name: Fail if there is no correct label
+        if: |
+          !contains(github.event.pull_request.labels.*.name, 'major')
+          || !contains(github.event.pull_request.labels.*.name, 'minor')
+          || !contains(github.event.pull_request.labels.*.name, 'patch')
+        run: |
+          echo "::group::Correct label NOT found"
+          echo "::endgroup::"
+          exit 1
 
       - name: Get supposed release version
         id: release_version
